services:
  php:
    image: ghcr.io/eventpoints/martinnewham.art-php:main
    volumes:
      - public_data:/app/public
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: 50s
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      MERCURE_PUBLIC_URL: "https://martinnewham.art/.well-known/mercure"
      DATABASE_URL: "postgresql://__MARTIN_NEWHAM_ART_POSTGRES_USER__:__MARTIN_NEWHAM_ART_POSTGRES_PASSWORD__@database:5432/__MARTIN_NEWHAM_ART_POSTGRES_DBNAME__?serverVersion=17&charset=utf8"
      MERCURE_JWT_SECRET: "__MARTIN_NEWHAM_ART_MERCURE_JWT_SECRET__"
      APP_SECRET: "__MARTIN_NEWHAM_ART_APP_SECRET__"
      MAILER_DSN: "__MARTIN_NEWHAM_ART_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__MARTIN_NEWHAM_ART_MESSENGER_TRANSPORT_DSN__"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/martinnewham.art-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__MARTIN_NEWHAM_ART_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__MARTIN_NEWHAM_ART_MERCURE_JWT_SECRET__"
    volumes:
      - public_data:/app/public
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.martinnewham.rule=Host(`martinnewham.art`, `www.martinnewham.art`)"
      - "traefik.http.routers.martinnewham.tls=true"
      - "traefik.http.routers.martinnewham.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__MARTIN_NEWHAM_ART_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__MARTIN_NEWHAM_ART_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__MARTIN_NEWHAM_ART_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.martinnewham-adminer.rule=Host(`adminer.martinnewham.art`)"
      - "traefik.http.routers.martinnewham-adminer.tls=true"
      - "traefik.http.routers.martinnewham-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  public_data:
  php_socket:
  caddy_data:
  caddy_config: